#lang racket
(define (variable? x) (symbol? x))
(define (same-variable? v1 v2)
  (and (variable? v1)
       (variable? v2)
       (eq? v1 v2)))
(define (sum? x)
  (and (pair? x) (eq? (car x) `+)))
(define (addend x) (cadr x))
(define augend caddr)
(define (product? x)
  (and (pair? x) (eq? (car x) `*)))
(define multiplier cadr)
(define multiplicand caddr)
(define (=number? exp num)
  (and (number? exp) (= exp num)))
(define (make-sum x y)
  (cond ((=number? x 0) y)
        ((=number? y 0) x)
        ((and (number? x) (number? y)) (+ x y))
        (else (list `+ x y))))
(define (make-product x y)
  (cond ((or(=number? x 0) (=number? y 0)) 0)
        ((=number? x 1) y)
        ((=number? y 1) x)
        ((and (number? x) (number? y)) (* x y))
        (else (list `* x y))))
(define (exponentiation? exp)
  (and (pair? exp) (eq? (car exp) `**)))
(define base cadr)
(define exponent caddr)
(define (make-exponetiation base exponent)
  ;(display base) (display exponent)
  (cond ((=number? exponent 1) base)
        ((=number? exponent 0) 1)
        (else (list `** base exponent))))
(define (deriv exp var)
  (cond ((number? exp) 0)
        ((variable? exp)
         (if (same-variable? exp var) 1 0))
        ((sum? exp)
         ;(display "make-sum")
         (make-sum (deriv (addend exp) var)
                   (deriv (augend exp) var)))
        ((product? exp)
         (make-sum
         (make-product (multiplier exp)
                       (deriv (multiplicand exp) var))
         (make-product (deriv (multiplier exp) var)
                       (multiplicand exp))))
        ((exponentiation? exp)
         (make-product
          (make-product
           (exponent exp)
           (make-exponetiation (exponent exp)
                               `(- ,(base exp) 1)))
          
          (deriv (base exp) var)))
        (else
         (error "unkonw expression type --DERIV" exp))))
;(deriv `(+ x 3) `x)
;(deriv `(* x y) `x)
;(deriv '(** (* x y) 6) 'x)
(deriv `(** x y) `x)