#lang racket
(define (or-gate2 a1 a2 output)
  (define (or-gate-procedure)
    (let ((a1-not (make-wire))
          (a2-not (make-wire))
          (c (make-wire)))
      (inverter a1 a1-not)
      (inverter a2 a2-not)
      (add-gate a1-not a2-not c)
      (inverter c output)
      ))
  (add-action! a1 or-action-procedure)
  (add-action! a2 or-action-procedure)
  `ok)
