#lang racket
(define (make-account n passwd)
  (let ((balance n)
        (count 0)
        (pwd passwd))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient balance"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (call-the-cops)
      (error "call-the-cops"))
    (define (dispatch p m)
      (if (eq? p pwd)
          (cond ((eq? m `withdraw) withdraw)
                ((eq? m `deposit) deposit)
                (else
                 (error "Unknow request -- MAKE-ACCOUNT")))          
          (error "Incorrect password")))
    dispatch))
(define acc (make-account 100 `hg))
((acc `hg `withdraw) 40)

((acc `ddd `deposit) 50)