#lang planet neil/sicp
(define (make-semaphore n)
  (let ((cell 0))
    (define (acquire)
      (if (> cell n)
          (acquire)
          (begin (set! cell (+ cell 1))
                 cell)))
    (define (release)
      (set! cell (- cell 1))
      cell)    
    (define (the-semaphore m)
      (cond ((eq? m `acquire) (acquire))            
            ((eq? m `release) (release))))
    the-semaphore))

(define s (make-semaphore 6))
(s `acquire)
(s `acquire)
(s `acquire)
(s `acquire)
(s `release)